# Generated by Django 5.1.1 on 2024-09-23 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message_text", models.CharField(max_length=256)),
                (
                    "pub_date",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date"),
                ),
            ],
        ),
    ]
