# Generated by Django 5.1.1 on 2024-10-06 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_text",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_text", models.TextField()),
                ("completion_tokens", models.PositiveIntegerField()),
                ("prompt_tokens", models.PositiveIntegerField()),
                ("total_price", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="project.message",
                    ),
                ),
            ],
        ),
    ]
