# Generated by Django 5.1.1 on 2024-10-10 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_alter_message_message_text_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
    ]
