# Generated by Django 5.1.1 on 2024-10-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_response_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="attached_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
